### PR TITLE
Use Path.stem instead of '/' literal

### PR DESCRIPTION
**Pull request by FObermaier**
This makes the whole project work on non-*nix platforms (e.g. Windows)

### CODE REVIEW

**Comment by mikel-brostrom** [comment]
Thank you for pointing this out @FObermaier. I however used `pathlib` to fix this so that the framework used for all paths manipulation are unified across the repo. I will acknowledge this in the next release. Thanks!

**Comment by FObermaier** [comment]
It does not work, wonder it works for you because if you use `Path.stem` you have to remove `.pt` from the URL keys.

**Comment by mikel-brostrom** [comment]
Sorry, `.stem` replaced by `.name` now

**Comment by FObermaier** [comment]
Thanks, it works on my machine now.

**Pull request closed without merging**
