### PR TITLE
Adding Bot SORT tracker

### PR DESCRIPTION
**Pull request by Mohit-robo**
This PR adds the `BoT-SORT` tracker to the tracker's list.
The `BoT-SORT` tracker added in this PR does not use any `Reid `model, and works similarly to `byte track`. 

Sample results:

https://user-images.githubusercontent.com/82194525/208481092-d760113e-fe7e-4c3f-8118-121b6a5b7ad2.mp4

### CODE REVIEW

**Comment by mikel-brostrom** [comment]
If there is not ReID feature extraction it must be almost identical to ByteTrack. Would it be possible for you to add the ReID feature extraction models provided by this repo? Here is the line of code you need:

https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/blob/10da55584c92a1851296afa271ecb3f5a608cdf8/trackers/strong_sort/strong_sort.py#L33

**Comment by Mohit-robo** [comment]
> If there is not ReID feature extraction it must be almost identical to ByteTrack. Would it be possible for you to add the ReID feature extraction models provided by this repo? Here is the line of code you need:
> 
> https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/blob/10da55584c92a1851296afa271ecb3f5a608cdf8/trackers/strong_sort/strong_sort.py#L33
> 
> Then we could compare it to StrongSORT add get it merged 😄. Otherwise it would be like having ByteTrack twice in the trackers folder

Thanks for the suggestions, will surely try it and get back to you

**Comment by mikel-brostrom** [comment]
Looking forward to review this :rocket:

**Comment by mikel-brostrom** [comment]
Let me know @Mohit-robo whenever this is reviewable :+1:

**Comment by Mohit-robo** [comment]
> Let me know @Mohit-robo whenever this is reviewable 👍

Yes sure, stuck with other things.

**Comment by Mohit-robo** [comment]
Please could you have a look at this:

https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/blob/f8a7bfebd568f766a6773774085c20deec310d89/trackers/bytetrack/matching.py#L195

raises an error when testing bytetrack.

**Comment by mikel-brostrom** [comment]
Weird. How is this even passing in the CI pipeline...

**Comment by mikel-brostrom** [comment]
Should be fixed now. `git pull` from master

**Comment by Mohit-robo** [comment]
> Should be fixed now. `git pull` from master

Okay

**Pull request closed without merging**
