### PR TITLE
SR-UKF for improved target tracking

### PR DESCRIPTION
**Pull request by henriksod**
Implemented draft of SR-UKF for improved target tracking.

https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.80.1421&rep=rep1&type=pdf

Needs to be tested.

### CODE REVIEW

**Comment by mikel-brostrom** [comment]
Some errors:

```bash
File "/datadrive/mikel/Yolov5_DeepSort_OSNet/strong_sort/sort/kalman_filter.py", line 127, in predict
    self._sigma_points[:, 1:(points-1)/2+1] = mean + self._gamma * covariance_sqrt
TypeError: slice indices must be integers or None or have an __index__ method
```

Another one when a make the indices to int:

```bash
File "/datadrive/mikel/Yolov5_DeepSort_OSNet/strong_sort/sort/kalman_filter.py", line 333, in _compute_covariance_square_root_from_sigma_points
    self._sigma_points[:, 0] - mean,
ValueError: operands could not be broadcast together with shapes (8,) (4,)
```

**Comment by henriksod** [comment]
It was supposed to say:
`sigma_points[:, 0] - mean,`

fixed

**Comment by mikel-brostrom** [comment]
I get the following results

Current KF:

> HOTA: 52.979
> MOTA: 59.983
> IDF1: 67.239

Proposed KF:

> HOTA: 49.843
> MOTA: 59.452
> IDF1: 62.138

**Comment by henriksod** [comment]
Seems like the EKF might be sufficient for bounding box tracking and that there is too much overhead in the SR-UKF for it to be useful for this application.

**Comment by Stephen-Ning** [comment]
> 似乎 EKF 可能足以用于边界框跟踪，并且 SR-UKF 的开销太大，无法用于此应用程序。

Hello, can I see your SR-UFK code?

**Comment by henriksod** [comment]
henriksod:feature/SR-UKF

**Comment by Stephen-Ning** [comment]
> henriksod：功能/SR-UKF

I found that the Kalman filtering code of the file you submitted is different from that of henriksod: SR-UKF. What is the reason?

**Comment by henriksod** [comment]
I suggest you check out this pull request instead,
https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/pull/489

Using UKF for a linear model is just not useful...

**Comment by Stephen-Ning** [comment]
thank you！

**Comment by henriksod** [comment]
Reopened a rebased version of #489  here:
https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/pull/596

**Comment by lhfabc9** [comment]
> Hello,have you done experiments with EKF?

**Comment by lhfabc9** [comment]
> Seems like the EKF might be sufficient for bounding box tracking and that there is too much overhead in the SR-UKF for it to be useful for this application.

Hello,have you done experiments with EKF?

**Comment by lhfabc9** [comment]
> No, I probably mistyped. The model is linear, so EKF == KF.

Can this model be changed to nonlinear?thank you！

**Comment by lhfabc9** [comment]
> Seems like the EKF might be sufficient for bounding box tracking and that there is too much overhead in the SR-UKF for it to be useful for this application.

Hello,did you use SR-UKF to change the original motion model to something like CTRV?

**Comment by henriksod** [comment]
Since we are not assuming any characteristics of the tracked objects, I did not look into other models. Maybe it can be worth looking into for more targeted applications?

**Comment by lhfabc9** [comment]
> Since we are not assuming any characteristics of the tracked objects, I did not look into other models. Maybe it can be worth looking into for more targeted applications?

Well, thank you

**Pull request closed without merging**
