### PR TITLE
Fixes to kalman filter and implementation for adaptive Q and R noise covariance estimation

### PR DESCRIPTION
**Pull request by henriksod**
Fixed noise covariance matrices so they are not varied based on bounding box location. Fixed delta time of predictions from constant 1 second to varied based on the frequency of predictions, this should increase performance.

Implemented adaptive kalman filter for Q and R estimation, based on
https://arxiv.org/ftp/arxiv/papers/1702/1702.00884.pdf

### CODE REVIEW

**Comment by mikel-brostrom** [comment]
Current KF:

> HOTA: 52.979
> MOTA: 59.983
> IDF1: 67.239

Proposed KF:

> HOTA: 52.642 (-0.337)
> MOTA: 59.826 (-0.157)
> IDF1: 66.289 (-0.950)

IDF1 took quite a hit

**Comment by henriksod** [comment]
Added initial noise addition along with dissipation factor. Please check again!

**Comment by mikel-brostrom** [comment]
One more:

`AttributeError: 'KalmanFilter' object has no attribute '_initial_error_scaling'`

**Comment by henriksod** [comment]
Fixed the naming issue

**Comment by henriksod** [comment]
Bump

**Comment by mikel-brostrom** [comment]
Will have a look at it this weekend :smile:

**Comment by henriksod** [comment]
Reopened a rebased version: https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/pull/596

**Pull request closed without merging**
